# Generated by Django 3.2.13 on 2022-05-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='statsviewers\\static\\statsviewers\\media\\img\\drivers')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('body', models.ManyToManyField(to='statsviewers.Bodies')),
            ],
        ),
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='statsviewers\\static\\statsviewers\\media\\img\\circuit')),
            ],
        ),
        migrations.CreateModel(
            name='Cup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='statsviewers\\static\\statsviewers\\media\\img\\cup')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='statsviewers\\static\\statsviewers\\media\\img\\drivers')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Gametype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Gliders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='statsviewers\\static\\statsviewers\\media\\img\\drivers')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Tires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='statsviewers\\static\\statsviewers\\media\\img\\drivers')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultat', models.IntegerField(default=1)),
                ('deco', models.BooleanField(default=False)),
                ('number_of_bots', models.IntegerField(default=0)),
                ('build', models.ManyToManyField(to='statsviewers.Build')),
                ('circuit', models.ManyToManyField(to='statsviewers.Circuit')),
                ('gametype', models.ManyToManyField(to='statsviewers.Gametype')),
            ],
        ),
        migrations.AddField(
            model_name='build',
            name='driver',
            field=models.ManyToManyField(to='statsviewers.Drivers'),
        ),
        migrations.AddField(
            model_name='build',
            name='glider',
            field=models.ManyToManyField(to='statsviewers.Gliders'),
        ),
        migrations.AddField(
            model_name='build',
            name='tire',
            field=models.ManyToManyField(to='statsviewers.Tires'),
        ),
    ]
