# Generated by Django 3.2.13 on 2022-05-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsviewers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gliders',
            new_name='Body',
        ),
        migrations.RenameModel(
            old_name='Bodies',
            new_name='Driver',
        ),
        migrations.RenameModel(
            old_name='Drivers',
            new_name='Glider',
        ),
        migrations.RenameModel(
            old_name='Tires',
            new_name='Tire',
        ),
        migrations.AddField(
            model_name='circuit',
            name='cup',
            field=models.ManyToManyField(to='statsviewers.Cup'),
        ),
    ]
