# Generated by Django 3.2.13 on 2022-05-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsviewers', '0002_auto_20220514_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='body',
            name='name',
        ),
        migrations.RemoveField(
            model_name='circuit',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cup',
            name='name',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='name',
        ),
        migrations.RemoveField(
            model_name='glider',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tire',
            name='name',
        ),
        migrations.AddField(
            model_name='body',
            name='en_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='body',
            name='fr_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='circuit',
            name='en_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='circuit',
            name='fr_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='cup',
            name='en_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='cup',
            name='fr_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='en_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='fr_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='glider',
            name='en_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='glider',
            name='fr_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='tire',
            name='en_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='tire',
            name='fr_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='body',
            field=models.ManyToManyField(blank=True, null=True, to='statsviewers.Body'),
        ),
        migrations.AlterField(
            model_name='build',
            name='driver',
            field=models.ManyToManyField(blank=True, null=True, to='statsviewers.Driver'),
        ),
        migrations.AlterField(
            model_name='build',
            name='glider',
            field=models.ManyToManyField(blank=True, null=True, to='statsviewers.Glider'),
        ),
        migrations.AlterField(
            model_name='build',
            name='tire',
            field=models.ManyToManyField(blank=True, null=True, to='statsviewers.Tire'),
        ),
        migrations.AlterField(
            model_name='circuit',
            name='cup',
            field=models.ManyToManyField(blank=True, null=True, to='statsviewers.Cup'),
        ),
        migrations.AlterField(
            model_name='course',
            name='build',
            field=models.ManyToManyField(blank=True, null=True, to='statsviewers.Build'),
        ),
        migrations.AlterField(
            model_name='course',
            name='circuit',
            field=models.ManyToManyField(blank=True, null=True, to='statsviewers.Circuit'),
        ),
        migrations.AlterField(
            model_name='course',
            name='deco',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='gametype',
            field=models.ManyToManyField(blank=True, null=True, to='statsviewers.Gametype'),
        ),
        migrations.AlterField(
            model_name='course',
            name='number_of_bots',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='resultat',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
