# Generated by Django 3.2.13 on 2022-05-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsviewers', '0003_auto_20220514_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultat', models.IntegerField(blank=True, default=1, null=True)),
                ('deco', models.BooleanField(blank=True, default=False, null=True)),
                ('number_of_bots', models.IntegerField(blank=True, default=0, null=True)),
                ('date_course', models.DateField(blank=True, null=True)),
                ('build', models.ManyToManyField(blank=True, null=True, to='statsviewers.Build')),
                ('circuit', models.ManyToManyField(blank=True, null=True, to='statsviewers.Circuit')),
                ('gametype', models.ManyToManyField(blank=True, null=True, to='statsviewers.Gametype')),
            ],
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
