# Generated by Django 3.2.13 on 2022-05-14 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statsviewers', '0004_auto_20220514_1729'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tracks',
            new_name='Courses',
        ),
    ]
