# Generated by Django 3.2.13 on 2022-05-14 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statsviewers', '0005_rename_tracks_courses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Circuit',
            new_name='Track',
        ),
    ]
